### ISSUE TITLE
Check FAQs

### ISSUE THREAD

**Issue by keeganmcbride** [keeganmcbride/jkan#44]

**Comment by infokujur** [comment]
Mis on riigi avaandmete portaal?

atm text is this:

Avaandmete portaali peamised ülesanded on:

- Otsida ja alla laadida ava-andmeid.
- Lisada uusi avaandmeid: selleks on eelnevalt vaja portaali registreeruda ja saada ligipääsõigus portaali haldaja käest.
- Kasutada andmehulkade hoidlat, mis on üks võimalikest kohtadest, kuhu avaandmeid salvestada.
- Kasutada ja leida avaandmete põhjal loodud rakendusi.
- Võimaldada avaandmete teemal uudiste, küsimuste, diskussioonide ja juhendite postitamine.

I would take some info away:

- Otsida ja alla laadida ava-andmeid.
- Lisada viiteid uutele avaandmetele.
- Kasutada ja leida avaandmete põhjal loodud rakendusi.
- Võimaldada avaandmete teemal uudiste, küsimuste, diskussioonide ja juhendite postitamine.

@andreskytt Should something to be added there?

**Comment by infokujur** [comment]
I made minor changes there:
https://github.com/keeganmcbride/jkan/blob/gh-pages/kkk.html

Some info need to be added in the future but good for now.

**Comment by infokujur** [comment]
Ok now all good: 
https://github.com/keeganmcbride/jkan/blob/gh-pages/kkk.html
