### ISSUE TITLE
Update about page 

### ISSUE THREAD

**Issue by keeganmcbride** [keeganmcbride/jkan#46]

**Comment by infokujur** [comment]
You mean this page? https://keeganmcbride.github.io/jkan/lisainfo/
That could be turened into about page (I didn't find it).

**Comment by keeganmcbride** [comment]
yes that is the page i meant, I changed some things around after making issue.

**Comment by infokujur** [comment]
This info is ok. Some things need to be added after working group workflow will be clear at the beginning of November.

**Comment by infokujur** [comment]
So you can rename - lisainfo to about - also in links. Didn't start to change it from here.
